[project]
name = "BBP_analysis"
version = "0.1.0"
description = "Scratch project analysis dashboard"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.5.0",
    "pandas>=2.2.3",
    "streamlit>=1.44.2",
    "yfinance>=0.2.55",
]
